### ISSUE TITLE
Restructure source file paths

### ISSUE THREAD

**Issue by wmcnamara** [Juptian/engine#1]
As of now the directory to get to the source paths is: *engine\Sparky game Engine\Sparky Game Engine*

which is not only long to type, but a bit of an annoyance for command-line interfaces especially when adding files with git. Can this get moved to a more simpler structure, maybe something along the lines of:

engine/src < with the src/ directory being where the CPP/H files are? It would make life easier, and make organizing project files far easier.

**Comment by Juptian** [comment]
I made it engine/SparkyGameEngine/Source

So I removed the spaces which is a QOL thing, and I also removed a middleman folder to make it easier
